# Jekyll 기본 설정
title: 나의 블로그
description: Jekyll로 만든 나만의 블로그입니다.
url: https://nametalk.github.io
baseurl: ""

# 빌드 설정
theme: jelly-theme-minimal

# 제외할 파일
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - .DS_Store
 
